name: Build and Release LogParser App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build LogParser app on Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --publish=never

      - name: Build LogParser app on Linux
        if: matrix.os == 'ubuntu-latest'
        run: npx electron-builder --linux --publish=never

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: log-parser-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.AppImage

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: log-parser-ubuntu-latest
          path: dist/*.AppImage

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: log-parser-windows-latest
          path: dist/*.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            ## Changes
            - Auto-generated release notes.
          draft: false
          prerelease: false

      - name: Upload Release Asset for Linux
        uses: actions/upload-release-asset@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.AppImage
          asset_name: log-parser-linux.AppImage
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.exe
          asset_name: log-parser-windows.exe
          asset_content_type: application/octet-stream
